osx_image: xcode10
language: objective-c
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_success: never
    on_failure: change
cache: cocoapods
install:
  - bundle install
script:
  - bundle exec fastlane travis
