osx_image: xcode10
language: objective-c
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_success: never
    on_failure: change
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --repo-update --project-directory=Example
install:
  - bundle install
script:
  - bundle exec fastlane test_framework
  - pod lib lint
